name: Docker Image CD

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and publish the Docker image
      run: |
        docker build . --file Dockerfile --tag dani666/pokermon:latest
        docker push dani666/pokermon:latest
